name: Publish to TestPyPI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-n-publish:
    name: Build and publish to TestPyPI
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install build tool
      run: python -m pip install build

    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/

    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip_existing: true
        password: ${{ secrets.TESTPYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
